apps/user/urls.py
#author_by zhuxiaoliang
#2018-12-21 下午8:08

from django.urls import path,re_path
from .views import Login,Register,Logout

app_name = 'user'



urlpatterns = [
    path('login/',Login.as_view(),name='login'),
    path('register/',Register.as_view(),name='register'),
    path('logout/',Logout.as_view(),name='logout'),

]

music/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
import xadmin

from music.settings import MEDIA_ROOT
from django.views.static import serve
from index.views import IndexView



urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('admin/', xadmin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('index/',include('index.urls',namespace='index')),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT }),
    path('play/', include('play.urls', namespace='play')),
]

源码v1.1/第11章/music/music/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('ranking.html', include('ranking.urls')),
    path('play/', include('play.urls')),
    path('comment/', include('comment.urls')),
    path('search/', include('search.urls')),
    path('user/', include('user.urls')),
    # 设置项目上线的静态资源路径
    url('^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static')
]


# 设置404、500错误状态码
from index import views
handler404 = views.page_not_found
handler500 = views.page_not_found

源码v1.1/第11章/music/user/urls.py
from django.urls import path
from . import views
urlpatterns = [
    # 用户的注册和登录
    path('login.html', views.loginView, name='login'),
    # 用户中心
    path('home/<int:page>.html', views.homeView, name='home'),
    # 退出用户登录
    path('logout.html', views.logoutView, name='logout'),
]

apps/user/models.py
from django.db import models

# Create your models here.

from  django.contrib.auth.models import AbstractUser

from datetime import datetime




class MyUser(AbstractUser):
    qq = models.CharField('QQ',max_length=20)
    webChat = models.CharField('微信',max_length=20)
    mobile = models.CharField('手机号',max_length=20,unique=True)

    class Meta:
        verbose_name  = "用户"
        verbose_name_plural = "用户"

    def __str__(self):
        return self.username

源码v1.1/第10章/第10.1章节/MyDjango/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=16)
    weChat = models.CharField('微信账号', max_length=100)
    mobile = models.CharField('手机号码', max_length=11)
    # 设置返回值
    def __str__(self):
        return self.username

源码v1.1/第10章/第10.2章节/MyDjango/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=16)
    weChat = models.CharField('微信账号', max_length=100)
    mobile = models.CharField('手机号码', max_length=11)
    # 设置返回值
    def __str__(self):
        return self.username

源码v1.1/第10章/第10.4章节/MyDjango/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=16)
    weChat = models.CharField('微信账号', max_length=100)
    mobile = models.CharField('手机号码', max_length=11)
    # 设置返回值
    def __str__(self):
        return self.username

源码v1.1/第10章/第10.5章节/MyDjango/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=16)
    weChat = models.CharField('微信账号', max_length=100)
    mobile = models.CharField('手机号码', max_length=11)
    # 设置返回值
    def __str__(self):
        return self.username

源码v1.1/第11章/music/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=20)
    weChat = models.CharField('微信账号', max_length=20)
    mobile = models.CharField('手机号码', max_length=11, unique=True)
    # 设置返回值
    def __str__(self):
        return self.username

源码v1.1/第13章/第13.2章节/MyDjango/user/models.py
from django.db import models

# Create your models here.

源码v1.1/第13章/第13.4章节/MyDjango/user/models.py
from django.db import models

# Create your models here.

源码v1.1/第2章/MyDjango/user/models.py
from django.db import models

# Create your models here.

源码v1.1/第3章/MyDjango/user/models.py
from django.db import models

# Create your models here.

源码v1.1/第4章/MyDjango/user/models.py
from django.db import models

# Create your models here.

源码v1.1/第6章/MyDjango/user/models.py
from django.db import models

# Create your models here.

源码v1.1/第9章/第9.1章节/MyDjango/user/models.py
from django.db import models

# Create your models here.

源码v1.1/第9章/第9.2章节/MyDjango/user/models.py
from django.db import models

# Create your models here.

源码v1.1/第9章/第9.3章节/MyDjango/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=16)
    weChat = models.CharField('微信账号', max_length=100)
    mobile = models.CharField('手机号码', max_length=11)
    # 设置返回值
    def __str__(self):
        return self.username

源码v1.1/第9章/第9.6章节/MyDjango/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=16)
    weChat = models.CharField('微信账号', max_length=100)
    mobile = models.CharField('手机号码', max_length=11)
    # 设置返回值
    def __str__(self):
        return self.username

apps/user/forms.py
#author_by zhuxiaoliang
#2018-12-21 下午7:54

from django import forms
from django.contrib.auth.forms import UserCreationForm
from  .models import MyUser




class MyUserForm(UserCreationForm):

    def __init__(self,*args,**kwargs):

        super().__init__(*args,**kwargs)
        self.fields['password1'].widget= forms.PasswordInput(attrs={
            'class': 'txt tabInput',
            'placeholder':'密码,4-16位数字/字母/特殊符号(空格除外)'
        })
        self.fields['password2'].widget = forms.PasswordInput(attrs={
            'class': 'txt tabInput',
            'placeholder':'重复密码'
        })


    class Meta:
        model = MyUser
        fields = UserCreationForm.Meta.fields +('mobile',)
        widgets = {
            'mobile': forms.widgets.TextInput(attrs={'class': 'txt tabInput', 'placeholder': '手机号'}),
            'username': forms.widgets.TextInput(attrs={'class': 'txt tabInput', 'placeholder': '用户名'}),
        }

源码v1.1/第13章/第13.2章节/MyDjango/user/forms.py
# 定义用户登录表单类
from django import forms
from captcha.fields import CaptchaField
class CaptchaTestForm(forms.Form):
    username = forms.CharField(label='用户名')
    password = forms.CharField(label='密码', widget=forms.PasswordInput)
    captcha = CaptchaField()

apps/user/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse

# Create your views here.
from django.views.generic import View

from .forms import MyUserForm
from .models import MyUser
from django.contrib.auth import authenticate,login,logout
from index.models import Dynamic


class Login(View):
    def get(self,request):
        return render(request, 'login.html', locals())
    def post(self,request):
        user = request.POST.get('username')
        password = request.POST.get('password')
        print(user,password)
        u = authenticate(username=user,password=password)

        if u:
            login(request,u)
            return redirect(reverse('index:home',args=[1,]))
        else:
            tips='用户名或密码错误'
            return render(request, 'login.html', locals())



class Register(View):
    def get(self,request):
        user = MyUserForm()
        return render(request, 'register.html', locals())
    def post(self,request):
        user = MyUserForm(request.POST)
        if user.is_valid():
            user.save()
            return  render(request, 'login.html', locals())
        else:
            tips = user.errors

            return render(request, 'register.html', locals())


class Logout(View):
    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse('user:login'))

源码v1.1/第10章/第10.1章节/MyDjango/user/views.py
from django.shortcuts import render, redirect
from .models import MyUser
from django.contrib.auth.models import Permission
from django.contrib.auth import login, authenticate, logout

# 用户登录
def loginView(request):
    tips = '请登录'
    title = '用户登录'
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        if MyUser.objects.filter(username=username):
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    # 登录当前用户
                    login(request, user)
                return redirect('/')
            else:
                tips = '账号密码错误，请重新输入'
        else:
            tips = '用户不存在，请注册'
    return render(request, 'user.html', locals())

# 用户注册
def registerView(request):
    title = '用户注册'
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        if MyUser.objects.filter(username=username):
            tips = '用户已存在'
        else:
            user = MyUser.objects.create_user(username=username, password=password)
            user.save()
            # 添加权限
            permission = Permission.objects.filter(codename='visit_Product')[0]
            user.user_permissions.add(permission)
            return redirect('/user/login.html')
    return render(request, 'user.html', locals())

# 退出登录
def logoutView(request):
    logout(request)
    return redirect('/')

apps/user/templates/login.html
{% extends "title_base.html" %}
{% block title  %}
{% load staticfiles %}
<link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/register.css" %}">
</head>

<body class="review">
<div class="wrapper">
    <div class="header clearfix">
        <a href="/" class="logo">我的音乐</a>
        <span class="logo-tip">Hi,我的音乐欢迎您!</span>
    </div>

    <div class="content clearfix">
        <!-- 登录注册版块 -->
        <div id="unauth_main" class="login-regist">
            <div class="login-box switch_box" style="display:block;">
                <div class="title">用户登录</div>
                <form id="loginForm" class="formBox" action="" method="post">
                    {% csrf_token %}
                    <div class="itembox user-name">
                        <div class="item">
                            <input type="text" name="username" placeholder="用户名或手机号" class="txt tabInput">
                        </div>
                    </div>
                    <div class="itembox user-pwd">
                        <div class="item">
                            <input type="password" name="password" placeholder="登录密码" class="txt tabInput">
                        </div>
                    </div>
                    {% if tips %}
                        <div>提示:<span>{{ tips }}</span></div>
                    {% endif %}
                    <div id="loginBtnBox" class="login-btn">
                        <input id="J_LoginButton" type="submit" value="马上登录" class="tabInput pass-btn" />
                    </div>
                    <div class="pass-reglink">还没有我的音乐账号？<a href="{% url 'user:register' %}">免费注册</a></div>
                </form>
            </div>
            <!-- //登录版块end -->

        </div>
    </div>
</div>
<script data-main="{% static "js/register.js" %}" src="{% static "js/require.js" %}"></script>
{% endblock  %}

apps/user/templates/register.html
{% extends "title_base.html" %}
{% block title  %}
{% load staticfiles %}
<link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/register.css" %}">
</head>

<body class="review">
<div class="wrapper">
    <div class="header clearfix">
        <a href="/" class="logo">我的音乐</a>
        <span class="logo-tip">Hi,我的音乐欢迎您!</span>
    </div>

    <div class="content clearfix">
        <!-- 登录注册版块 -->
<div></div>
                <form id="" class="formBox" method="post" action="">
                    {% csrf_token %}
                    <div id="registForm" class="formBox">
                    <div class="itembox user-name">
                    <div class="item">
                        {{ user.username }}
                    </div>
                    </div>
                    <div class="itembox user-name">
                    <div class="item">
                        {{ user.mobile }}
                    </div>
                    </div>
                    <div class="itembox user-pwd">
                    <div class="item">
                        {{ user.password1 }}
                    </div>
                    </div>
                    <div class="itembox user-pwd">
                    <div class="item">
                        {{ user.password2 }}
                    </div>
                    </div>
                    {% if tips %}
                        <div>提示:<span>{{ tips }}</span></div>
                    {% endif %}
                    <div class="member-pass clearfix">
                        <input id="agree" name="agree" checked="checked" type="checkbox" value="1"><label for="agree" class="autologon">已阅读并同意用户注册协议</label>
                    </div>
                        <input type="submit" value="免费注册" id="J_RegButton" class="pass-btn tabInput"/>
                        <div class="pass-reglink">已有我的音乐帐号，<a href="{% url 'user:login' %}">立即登录</a></div>
                    </div>



<script data-main="{% static "js/register.js" %}" src="{% static "js/require.js" %}"></script>
{% endblock  %}